version: '3.8'

services:
  app:
    image: node:16
    container_name: my_node_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret_key
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name
    depends_on:
      - db
    command: npm start

  db:
    image: mysql:8
    container_name: my_mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=your_db_password
      - MYSQL_DATABASE=your_db_name
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
